// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using entity.sql.importacao.Models;

namespace entity.sql.importacao.Migrations
{
    [DbContext(typeof(EFContext))]
    partial class EFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("entity.sql.importacao.Models.NFeDetItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CEan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEantrib")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CProd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cfop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndEscala")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndTot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ncm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotaFiscalId")
                        .HasColumnType("int");

                    b.Property<string>("QCom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QTrib")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UCom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UTrib")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VProd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VTotTrib")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VUnCom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VUnTrib")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XProd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NotaFiscalId");

                    b.ToTable("tb_nfe_det_item");
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeDetPag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IndPag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NFePagId")
                        .HasColumnType("int");

                    b.Property<string>("TPag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TpIntegra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VPag")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NFePagId");

                    b.ToTable("tb_nfe_detalhe_pagamento");
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeEmi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Crt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotaFiscalId")
                        .HasColumnType("int");

                    b.Property<string>("XFant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XNome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NotaFiscalId");

                    b.ToTable("tb_nfe_emitente");
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeEndEmi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CMun")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NFeEmiId")
                        .HasColumnType("int");

                    b.Property<string>("Nro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XBairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XCpl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XLgr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XMun")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NFeEmiId");

                    b.ToTable("tb_nfe_end_emitente");
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeIde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CDv")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("CMunFg")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("CNf")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("CUf")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("DhEmi")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("FinNfe")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("IdDest")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("IndFinal")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("IndPres")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Mod")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NNf")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NatOp")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int>("NotaFiscalId")
                        .HasColumnType("int");

                    b.Property<string>("ProcEmi")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Serie")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("TpAmb")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("TpEmis")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("TpImp")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("TpNf")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("VerProc")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NotaFiscalId");

                    b.ToTable("tb_nfe_ide");
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeImpCofins", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NFeDetItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NFeDetItemId");

                    b.ToTable("tb_nfe_imp_cofins");
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeImpCofinsAliq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NFeImpCofinsId")
                        .HasColumnType("int");

                    b.Property<string>("PCofins")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VCofins")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NFeImpCofinsId");

                    b.ToTable("tb_nfe_imp_cofins_aliq");
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeImpCofinsNt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NFeImpCofinsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NFeImpCofinsId");

                    b.ToTable("tb_nfe_imp_cofins_nt");
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeImpIcms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Csosn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NFeDetItemId")
                        .HasColumnType("int");

                    b.Property<string>("Orig")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NFeDetItemId");

                    b.ToTable("tb_nfe_imp_icms");
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeImpPis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NFeDetItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NFeDetItemId");

                    b.ToTable("tb_nfe_imp_pis");
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeImpPisAliq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NFeImpPisId")
                        .HasColumnType("int");

                    b.Property<string>("PPis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VPis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NFeImpPisId");

                    b.ToTable("tb_nfe_imp_pis_aliq");
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeImpPisNt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NFeImpPisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NFeImpPisId");

                    b.ToTable("tb_nfe_imp_pis_nt");
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeInfAdic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InfAdFisco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InfCpl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotaFiscalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NotaFiscalId");

                    b.ToTable("tb_nfe_inf_adicional");
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeInfSupl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NotaFiscalId")
                        .HasColumnType("int");

                    b.Property<string>("QrCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlChave")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NotaFiscalId");

                    b.ToTable("tb_nfe_inf_suplementar");
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFePag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NotaFiscalId")
                        .HasColumnType("int");

                    b.Property<string>("VTroco")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NotaFiscalId");

                    b.ToTable("tb_nfe_pagamento");
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeProtNfe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CStat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChNfe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DhRecbto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DigVal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NProt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotaFiscalId")
                        .HasColumnType("int");

                    b.Property<string>("TpAmb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerAplic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XMotivo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NotaFiscalId");

                    b.ToTable("tb_nfe_protocolo_nfe");
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeSignature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CanonicalizationMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DigestMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DigestValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotaFiscalId")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignatureMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignatureValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transform1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transform2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("X509certificate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NotaFiscalId");

                    b.ToTable("tb_nfe_signature");
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeTotalIcms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NotaFiscalId")
                        .HasColumnType("int");

                    b.Property<string>("QrCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VBc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VBcst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VCofins")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VFcp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VFcpst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VFcpstret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VFrete")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VIcms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VIcmsdeson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VIi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VIpi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VIpidevol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VNf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VOutro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VPis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VProd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VSeg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VSt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VTotTrib")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NotaFiscalId");

                    b.ToTable("tb_nfe_total_icms");
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeTransp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NotaFiscalId")
                        .HasColumnType("int");

                    b.Property<string>("modFrete")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NotaFiscalId");

                    b.ToTable("tb_nfe_transportadora");
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NotaFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InfNfe")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Versao")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("tb_nota_fiscal");
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeDetItem", b =>
                {
                    b.HasOne("entity.sql.importacao.Models.NotaFiscal", "NotaFiscal")
                        .WithMany("NFeDetItem")
                        .HasForeignKey("NotaFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeDetPag", b =>
                {
                    b.HasOne("entity.sql.importacao.Models.NFePag", "NFePag")
                        .WithMany()
                        .HasForeignKey("NFePagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeEmi", b =>
                {
                    b.HasOne("entity.sql.importacao.Models.NotaFiscal", "NotaFiscal")
                        .WithMany()
                        .HasForeignKey("NotaFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeEndEmi", b =>
                {
                    b.HasOne("entity.sql.importacao.Models.NFeEmi", "NFeEmi")
                        .WithMany()
                        .HasForeignKey("NFeEmiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeIde", b =>
                {
                    b.HasOne("entity.sql.importacao.Models.NotaFiscal", "NotaFiscal")
                        .WithMany()
                        .HasForeignKey("NotaFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeImpCofins", b =>
                {
                    b.HasOne("entity.sql.importacao.Models.NFeDetItem", "NFeDetItem")
                        .WithMany()
                        .HasForeignKey("NFeDetItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeImpCofinsAliq", b =>
                {
                    b.HasOne("entity.sql.importacao.Models.NFeImpCofins", "ImpCofins")
                        .WithMany()
                        .HasForeignKey("NFeImpCofinsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeImpCofinsNt", b =>
                {
                    b.HasOne("entity.sql.importacao.Models.NFeImpCofins", "ImpCofins")
                        .WithMany()
                        .HasForeignKey("NFeImpCofinsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeImpIcms", b =>
                {
                    b.HasOne("entity.sql.importacao.Models.NFeDetItem", "NFeDetItem")
                        .WithMany()
                        .HasForeignKey("NFeDetItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeImpPis", b =>
                {
                    b.HasOne("entity.sql.importacao.Models.NFeDetItem", "NFeDetItem")
                        .WithMany()
                        .HasForeignKey("NFeDetItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeImpPisAliq", b =>
                {
                    b.HasOne("entity.sql.importacao.Models.NFeImpPis", "NFeImpPis")
                        .WithMany()
                        .HasForeignKey("NFeImpPisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeImpPisNt", b =>
                {
                    b.HasOne("entity.sql.importacao.Models.NFeImpPis", "NFeImpPis")
                        .WithMany()
                        .HasForeignKey("NFeImpPisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeInfAdic", b =>
                {
                    b.HasOne("entity.sql.importacao.Models.NotaFiscal", "NotaFiscal")
                        .WithMany()
                        .HasForeignKey("NotaFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeInfSupl", b =>
                {
                    b.HasOne("entity.sql.importacao.Models.NotaFiscal", "NotaFiscal")
                        .WithMany()
                        .HasForeignKey("NotaFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFePag", b =>
                {
                    b.HasOne("entity.sql.importacao.Models.NotaFiscal", "NotaFiscal")
                        .WithMany()
                        .HasForeignKey("NotaFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeProtNfe", b =>
                {
                    b.HasOne("entity.sql.importacao.Models.NotaFiscal", "NotaFiscal")
                        .WithMany()
                        .HasForeignKey("NotaFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeSignature", b =>
                {
                    b.HasOne("entity.sql.importacao.Models.NotaFiscal", "NotaFiscal")
                        .WithMany()
                        .HasForeignKey("NotaFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeTotalIcms", b =>
                {
                    b.HasOne("entity.sql.importacao.Models.NotaFiscal", "NotaFiscal")
                        .WithMany()
                        .HasForeignKey("NotaFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("entity.sql.importacao.Models.NFeTransp", b =>
                {
                    b.HasOne("entity.sql.importacao.Models.NotaFiscal", "NotaFiscal")
                        .WithMany()
                        .HasForeignKey("NotaFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
